artifacts_root: artifacts

data ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/tapankhaladkar/NLP-Text-Summarizer/raw/refs/heads/main/data/summarizer-data.zip
  local_data_file: artifacts/data_ingestion/summarizer-data.zip
  unzip_dir: artifacts/data_ingestion
